name: ecologyhydro
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - natcap.invest=3.20.2
  - gdal=3.10.*
  - numpy>=1.26,<3
  - pandas>=2,<4
  - scipy
  - netcdf4>=1.7,<2
  - pygeoprocessing>=2.4.10,<3
  - taskgraph>=0.11,<1
  - pyyaml>=6,<7
  - pydantic>=2,<3
  - psutil>=5.6.6,<8
  - pytest
  - ruff
  - uv
  - pip
  - setuptools>=75
